python3 seriesplots.py ../tests/real/optout/ tts 0
python3 seriesplots.py ../tests/real/optout/ aap 0
python3 seriesplots.py ../tests/real/optout/ apan 0
python3 seriesplots.py ../tests/real/shuttle/ tts 0
python3 seriesplots.py ../tests/real/shuttle/ aap 0
python3 seriesplots.py ../tests/real/shuttle/ apan 0
python3 seriesplots.py ../tests/real/yahoo/ tts 0
python3 seriesplots.py ../tests/real/yahoo/ aap 0
python3 seriesplots.py ../tests/real/yahoo/ apan 0
python3 seriesplots.py ../tests/real/swan/ tts 0
python3 seriesplots.py ../tests/real/swan/ aap 0
python3 seriesplots.py ../tests/real/swan/ apan 0
